version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aerostream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abir
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fake_api:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install fastapi uvicorn faker && python fastapi_tweet.py"
    ports:
      - "8001:8001"

  api:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install fastapi uvicorn sentence-transformers scikit-learn joblib && python api.py"
    ports:
      - "8000:8000"

  airflow:
    image: apache/airflow:2.7.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:abir@postgres/aerostream
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/app
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install psycopg2-binary requests &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com 2>/dev/null || true &&
      airflow standalone
      "
    depends_on:
      - postgres
      - fake_api
      - api

  dashboard:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install streamlit psycopg2-binary pandas plotly && streamlit run dashboard.py --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data: